name = "edgetunnel"
main = "_worker.js"
compatibility_date = "2025-04-14"
compatibility_flags = [ "nodejs_compat" ]

[vars]
# 这里可以填你自己的 UUID
UUID = "69ff7b2e-5cbc-4c43-a3b1-ec3ae3db3a69"
# 伪装域名
HOST = "www.cloudflare.com"
# 端口（Cloudflare Workers 固定 443/80，可不改）
PORT = 443

[build]
upload_sourcemaps = false

[[rules]]
type = "ESModule"
globs = ["**/*.js"]
