name = "black-block-72b6"
main = "_worker.js"
compatibility_date = "2026-04-14"
compatibility_flags = ["nodejs_compat"]

# 保留你的自定义域名
[[routes]]
pattern = "1.lllll2026.cc.cd"
zone_name = "lllll2026.cc.cd"
custom_domain = true

# 绑定环境变量
[vars]
ADMIN = "123"
UUID = "bd8353ad-17a3-4e52-bfb6-55ed35518f6a"

# 绑定KV（如果需要）
[[kv_namespaces]]
binding = "KV"
id = "e7d837d42b8d41468a1ce99beeae515a"
